Minimal viable
anvilproject/drs_downloader pull request #12
Opened 2022-11-07 20:05 UTC by matthewpeterkort

code review

2022-11-07 20:30 UTC, bwalsh commented
Two things:
* We should fix the conflicting files with the target branch:
* We should consider squashing commits

2022-11-07 20:38 UTC, matthewpeterkort commented
feature/setup branch doesn't need DRSClient.py that can be deleted from feature/setup. feature/setup uses cli.py as the driver file, but this file could be migrated over to main.py in the minimal viable branch, since that seems to be the driver file in the minimal viable branch. File structure is very different between the two branches.

2022-11-07 21:38 UTC, bwalsh requested changes
Let's discuss after all have reviewed.

2022-11-07 21:38 UTC, bwalsh commented on drs_downloader/Gen3DRSClient.py
>  class crdcDRSClient(Gen3DRSClient):
Re.  these xxxDRSClient classes.  OK to leave in for now?   Let's discuss use case.   Thinking we may want to discard for now and add back in after MVP.

2022-11-07 21:38 UTC, bwalsh commented on drs_downloader/download.py
>  #     #     exit(1)
Remove commented test code

2022-11-07 21:38 UTC, bwalsh commented on tests/test_drs_downloader.py
> +    object_url = 'https://development.aced-idp.org/ga4gh/drs/v1/objects/d62af3ff-756d-4e73-b6c6-e0bbd3bae50d'
OK for now.  We may need to rethink before release.   (prefer that we don't have to keep a test server up)

2022-11-08 23:40 UTC, bwalsh requested changes

2022-11-08 23:40 UTC, bwalsh commented on README.md
* Add instructions on how to become a member of our test terra project: https://anvil.terra.bio/#workspaces/anvil-stage-demo/DRS-downloader/data](https://anvil.terra.bio/#workspaces/anvil-stage-demo/DRS-downloader/data

* Add instructions or a link to gcloud setup
* Add instructions to link to the `NHLBI BioData Catalyst Framework Services`.   including `=google` hack

2022-11-09 14:14 UTC, bwalsh commented on drs_downloader/main.py
> +async def _get_more(session: aiohttp.ClientSession, uri: str, endpoint: str) -> DownloadURL:
"_get_more" is a bit non-specific.  can we use a more descriptive name?

2022-11-09 14:37 UTC, bwalsh commented on drs_downloader/download.py
>  async def _download(urls: List[DownloadURL], dest: Path):
The data class DownloadURL should be renamed to something that describes its contents.
See [DrsObject](https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.0.0/docs/#_drsobject)

2022-11-10 00:43 UTC, bwalsh commented on drs_downloader/download.py
>  async def _download(urls: List[DownloadURL], dest: Path):
Line 86: `assert expected_md5 == actual_md5, f"Actual md5 {actual_md5} does not match expected {expected_md5}"` should not be uncommented

2022-11-10 01:15 UTC, bwalsh commented on drs_downloader/download.py
>  async def _download(urls: List[DownloadURL], dest: Path):
There was a bug in the initial downloader.py


```def parts_generator(size, start=0, part_size=1 * 512 ** 2):
    while size - start > part_size:
        yield start, start + part_size
        start += part_size + 1
    yield start, size
```

2022-11-10 01:29 UTC, bwalsh commented
* review and merge PR#4
* start new branch locally "feature/mvp"
* See my comments starting here: https://github.com/anvilproject/drs_downloader/pull/12#pullrequestreview-1173061783
* The new branch should only have a minimum number of files, perhaps only:
```drs_downloader/download.py
drs_downloader/main.py
tests/test_main.py
tests/terra-data.tsv```

2022-11-12 02:30 UTC, closed without merging

2022-11-12 02:44 UTC, lbeckman314 commented
Closed for #16, all comments above should be resolved in #16.